### ISSUE TITLE
Support for earlier version of IE

### ISSUE THREAD

**Issue by rhache** [LeaVerou/prefixfree#1]
It mentions support for IE9 and above, but what about earlier version of IE? Is there any partial support? In particular I'm thinking of gradients.

Thanks,
Rene

**Comment by LeaVerou** [comment]
No, this is not a CSS polyfill that adds features in browsers that don't support them. Take a look at CSS3PIE for that (http://css3pie.com/). PrefixFree only takes care of prefixes and given its nature, I don't want to add any additional functionality to it, as it has to be super light.

**Comment by codler** [comment]
CSS3 finalize ( https://github.com/codler/jQuery-Css3-Finalize ) has partial support for gradients from IE7+
