### ISSUE TITLE
Add support for input-placeholder

### ISSUE THREAD

**Issue by smares** [LeaVerou/prefixfree#101]
Any chance you can add support for styling the input placeholder? AFAIK, following works:

:-ms-input-placeholder for IE 10+
:-moz-placeholder for Firefox 4+
::-webkit-input-placeholder for Chrome and Safari

**Comment by LeaVerou** [comment]
AFAIK it's non-standard so no.
Feel free to reopen once something like this gets in a W3C spec, or even draft.

**Comment by serverwentdown** [comment]
@smares For Firefox 19+ it's ::-moz-placeholder with two colons (pseudo element).

**Comment by nick4fake** [comment]
Please, add this thing. There are many use cases when we can not avoid input-placeholder

**Comment by LeaVerou** [comment]
You can add it pretty easily as a plugin, but I can’t add non-standard things to -prefix-free as a policy. Furthermore, PF doesn’t modify syntax, it just adds prefixes. In this case, the syntax is different too.

**Comment by nick4fake** [comment]
@LeaVerou do you mean that linear-gradient not supported too? Syntax is different for old browsers (old webkit)

**Comment by LeaVerou** [comment]
Not sure what you mean by “not supported”. Prefixes are added, but different syntax needs to be included separately (without a prefix). The only exception is angles, since there’s no way to determine whether they are new or old angles, so they are assumed to be new and converted for prefixed implementations. (see also: http://lea.verou.me/2012/07/important-prefix-free-update/ )

**Comment by nick4fake** [comment]
@LeaVerou sorry, if I add support for placeholders, it will not be merged before draft?

**Comment by LeaVerou** [comment]
No, but nothing prevents you from writing a plugin and publishing it somewhere :)
-prefix-free was made to be extensible, so it's really easy to write plugins. However, I’m very skeptical about adding things to the core, as it’s client-side so I need to keep it tiny and fast.
