### ISSUE TITLE
Linear gradient angles not working

### ISSUE THREAD

**Issue by nearestnabors** [LeaVerou/prefixfree#106]
Chrome Version 21.0.1180.89

My CSS:
background: linear-gradient(90deg, rgba(0, 0, 0, 0.25), transparent 75%);

CSS I get:
background: -webkit-linear-gradient(0deg, rgba(0, 0, 0, 0.25), transparent 75%);

Notice that "90deg" has become "0deg". Not sure if this is just a Chrome thing. But it's a thing nonetheless!

**Comment by LeaVerou** [comment]
It’s not a bug, it’s a feature: http://lea.verou.me/2012/07/important-prefix-free-update/

**Comment by nearestnabors** [comment]
Ha! So it is!
