### ISSUE TITLE
Prefixfree causes console warnings when used with Typekit

### ISSUE THREAD

**Issue by seanami** [LeaVerou/prefixfree#108]
At Typekit, we recently had a support ticket from a customer who noticed cross-domain XHR warnings in his console related to Typekit urls. We eventually tracked the root of the issue to prefixfree. Typekit dynamically adds a CSS link on use.typekit.net to the page (which loads the fonts), and it seems that prefixfree is then trying to grab this CSS via XHR in order to try to apply vendor prefixes. We don't have CORS headers set up since this CSS shouldn't be grabbed in this way, and thus the warning is triggered.

Should prefixfree ignore CSS files that don't come from the same origin as the page? Or should there be a feature to ignore CSS files from a configurable list of host names? I think either of these ideas would address the issue, but there may be other possible solutions as well.

**Comment by mkantor** [comment]
See #35 for some related discussion.

**Comment by LeaVerou** [comment]
Why are you telling people to add an extra stylesheet instead of just an `@import`? Google web fonts does the same (by default) and it’s really annoying.

Regarding the issue, the error thrown doesn't actually cause any problems and IIRC it can't be supressed by catching. So, the only way to avoid having it would be to check if the request is cross origin AND without CORS before sending it. But you have no way of knowing if CORS is enabled on it, until you actually make it!

**Comment by seanami** [comment]
People using the Typekit service actually include a JS file, which then determines which particular fonts the browser will need and adds a stylesheet link tag with the appropriate url to load them.

I realize that it'd be impossible to catch or suppress that warning, given that you'd have to know about CORS support before sending the request. At a higher level, I was suggesting that not every CSS asset on the page needs (or should) have its vendor prefixes managed by this script. It's fine if all CSS on the page is opted-in to start, but it might be useful (in cases like this) to give devs a way to opt certain CSS resources out of the prefixfree vendor prefix management. In effect, saying "This CSS resource has its vendor prefixes managed by someone else, so we don't need to (and shouldn't) do anything."

Just an idea. The warning isn't the end of the world, for sure.

**Comment by LeaVerou** [comment]
Oh but there is an opt-out :)
Just add `data-noprefix` to the link tag :)

**Comment by seanami** [comment]
Ah, I see. Unfortunately, the CSS link we add is automatically added to the page, so the dev can't add properties to it herself very easily. However, it is possible to add some JS immediately after the Typekit code that finds the new link tag and adds the `data-noprefix` attribute. I'll go ahead and suggest this to the user and add it to our support docs.

Thanks Lea!

**Comment by marcing** [comment]
We solved it like this:

```
    <script type="text/javascript">
        try
        {
            Typekit.load();
            // fix for prefixfree and typekit
            $('head').find('link[rel=stylesheet]:last').attr('data-noprefix', true);
        }catch(e){}
    </script>
```
