### ISSUE TITLE
calc() is not prefixed in Safari 6

### ISSUE THREAD

**Issue by mgol** [LeaVerou/prefixfree#111]
While `calc()` is properly prefixed in newest Chrome, it's not in Safari 6. Since Safari requires a prefix, it makes calc not work unless prefixed explicitely.

**Comment by mgol** [comment]
I initially reported it in a comment to bug #77 but since that bug was about Chrome which works fine for me I decided to open a separate bug report.

**Comment by mgol** [comment]
Hmm, I have to investigate more. Here's a simple test (I extracted relevant parts from -prefix-free code):

```
var style = document.createElement('div').style;
style.width = 'calc(1px + 5%)';
console.log(style.width);
style.width = '-webkit-calc(1px + 5%)';
console.log(style.width);
style.width = '5%';
console.log(style.width);
```

In Chrome it prints:

```

-webkit-calc(1px + 5%)
5%
```

In Safari first two lines are empty, the last one works.

It seems like Safari doesn't apply `calc` in certain conditions. It's weird because it accepts non-calc values and `-webkit-calc` works on Safari on my simple site. I'll try to find more info about it, I just thought these few remarks might be useful

**Comment by mgol** [comment]
Just tried it in Safari console:

```
prompt> div
<div style="width: -webkit-calc(1px + 5%); position: absolute; "></div>
prompt> div.style.cssText
"width: ; position: absolute; "
```

Something is seriously screwed up in Safari...

**Comment by mgol** [comment]
That's even worse - if you have an element styled as follows:

```
selector {
    width: -webkit-calc(1px + 5%);
    height: -webkit-calc(3px + 10%);
}
```

then styles are applied correctly. But once you assign anything to element's `style.height`, `style.width` is set to an empty string... I guess `calc()` can't be currently reliably used in Safari... :(

**Comment by mkantor** [comment]
Maybe this should be reported in the Safari (or WebKit?) bug tracker.

**Comment by mgol** [comment]
Sorry for the delay, I got quite busy recently. :/

I was just going to report it to the WebKit bugtracker but the problem doesn't exist in WebKit nightly so I guess they have fixed it.

Unfortunately, Safari is not on rapid release so we'll have to wait some time before it gets fixed on stable... :/

Well, in its current state `calc()` is unusable in Safari so there's nothing to change on `-prefix-free`'s side.
