### ISSUE TITLE
Prefix free won't work in the latest firefox (16.1)

### ISSUE THREAD

**Issue by mcmnet** [LeaVerou/prefixfree#113]
Having troubles getting the PrefixFree script to work in the latest FireFox 16.1 update.
Seems I'm having to use the manual way of doing it, which is prefixing with -moz- but not sure why this still works if the scipt doesn't.

Can anyone help?

Thanks
Jade

**Comment by LeaVerou** [comment]
Please define "does not work". If it's about gradients, look here: http://lea.verou.me/2012/07/important-prefix-free-update/

If it's about something else, please provide example code.

I'm pretty sure I've tested it recently in Firefox.

**Comment by niteangel** [comment]
It doesn't work perfectly on my Firefox 16.0.2, especially the background-gradient part. I have a screenshot of that on the test-drive page: http://d.pr/i/wcCm which shows that background gradient section is not "-moz-"-ified.

Please have a look.

**Comment by LeaVerou** [comment]
Firefox 16 supports unprefixed gradients, with the standard syntax, which is slightly different.
