### ISSUE TITLE
radial-gradient is not working on mozilla browser

### ISSUE THREAD

**Issue by bhargav2785** [LeaVerou/prefixfree#117]
I have a DIV that has radial-gradient as background-image. It uses prefix-free to determine which prefix to use. But somehow it works on -webkit- and -o- browsers but doesn't do anything on -moz-. Is it expecting other syntax? As per https://developer.mozilla.org/en-US/docs/CSS/radial-gradient it should hava the same syntax as background-image: -webkit-radial-gradient(45px 45px, ellipse farthest-corner, aqua 0%, rgba(0, 0, 255, 0) 100%, blue 95%); 

Below is the example on dabblet that uses prefix-free to decorate background image of that div with class=radial. This example does't work on Mozilla but works on Chrome, Safari and Opera.

http://dabblet.com/gist/4006129 

Thanks

**Comment by LeaVerou** [comment]
Hi,

Yes, the syntax is different for every browser that uses unprefixed gradients. You should specify both, even when using -prefix-free (just omit the prefix). Also see here, it's kind of relevant: http://lea.verou.me/2012/07/important-prefix-free-update/

**Comment by bhargav2785** [comment]
Thanks!! That helped.
