### ISSUE TITLE
Page keeps loading

### ISSUE THREAD

**Issue by AdmireNL** [LeaVerou/prefixfree#118]
When prefixfree is activated in some of my websites, the page sometimes keeps on loading and loading. All elements are loaded, except the scripts. Without prefixfree it's all fine. Any clues what's causing this?

**Comment by LeaVerou** [comment]
Never heard of this before. Are you sure it only happens with -prefix-free? Doesn't seem related to me.

**Comment by AdmireNL** [comment]
I'll try to have an example online soon, that can be examined. Right now it's still kinda secret.

**Comment by christianbundy** [comment]
Chrome Developer Tools has a way to see what's loading - check that and let us know what you see.

**Comment by AdmireNL** [comment]
The problem only seems to be present in Firefox, when you refresh the page (that happens a lot during development), it keeps sometimes loading on the scripts.

Can I please contact one of you by e-mail, since this project cannot be in the open?
