### ISSUE TITLE
No support for sticky positioning

### ISSUE THREAD

**Issue by Jab2870** [LeaVerou/prefixfree#123]
At the moment we still have to manually enter prefixes if we want something to have position:sticky.  As far as I know it is currently only a webkit feature but I am sure other browsers will start to support it before too long.  (well maybe not ie).  You can read about it here http://updates.html5rocks.com/2012/08/Stick-your-landings-position-sticky-lands-in-WebKit

It says in this article that it is only in chrome canary but stable chrome has now reached version 23 and i can confirm that if the experimental webkit features flag is enabled it works in this version.

**Comment by leeola** [comment]
:+1:

**Comment by LeaVerou** [comment]
Hi,

The purpose of -prefix-free is to enable you to write standards-compliant code, not to save you from typing prefixes in proprietary features. Feel free to reopen this bug once there is a spec (even an Editor’s Draft would do) for position:sticky, and I will add it. Currently there isn't one.

**Comment by yisibl** [comment]
Although there are no standard, but for developers who really is a very useful feature, Firefox 26 has achieved this keyword.

http://coreyford.name/files/position-sticky-presentation/

**Comment by LeaVerou** [comment]
I’m sorry, but non-standard things will never make it to -prefix-free as I believe they _should_ be written with prefixes.

**Comment by yisibl** [comment]
@LeaVerou Thanks! Where do you go to work?

**Comment by w4** [comment]
https://drafts.csswg.org/css-position/Overview.html#sticky-pos
