### ISSUE TITLE
Support for Gradient - Firefox

### ISSUE THREAD

**Issue by MartinMuzatko** [LeaVerou/prefixfree#128]
Hi!
I created a jsfiddle testcase ( http://jsfiddle.net/95BLE/9/ ) with the latest prefixfree.js included to test the linear-gradient CSS3 feature.

Unfortunatly I have ran into a few problems.

I have used prefixfree for a long time now, having no problems at all.
At some point the inclusion for new projects didn't work, and also I noticed that the support for my older projects I havn't touched in a while, had no support for gradients all of a sudden.

Please tell me what is wrong with the testcase and why it does not work, even though it should be supported without prefix.

Thank you in advance!

**Comment by ryanilg** [comment]
I noticed this issue today as well. I am using FF 16.0.2 on OSX.

It seems to be an issue with Firefox, possibly reporting that it supports "linear-gradient", even though it actually doesn't. 

Even older sites I have used prefix-free on are not showing gradients either, and I have not updated the prefixfree js recently so it's definitely not an issue with a change in the  "newer" version of the plugin.

**Comment by LeaVerou** [comment]
Firefox 16 does not need -prefix-free for gradients, it supports the newer standard syntax, without a prefix. If your gradients don’t work, it’s because they are using a slightly order syntax. Read more: http://lea.verou.me/2012/07/important-prefix-free-update/
