### ISSUE TITLE
Node not found in onreadystatechange

### ISSUE THREAD

**Issue by verlok** [LeaVerou/prefixfree#13]
Using the minified version of 1.0.3, I get this error "Node was not found" on FF, and "Uncaught Error: NOT_FOUND_ERR: DOM Exception 8" on Chrome, appearently about: window.PrefixFree.process.link.e.onreadystatechange

**Comment by LeaVerou** [comment]
Does it also happen with the unminified version? If so, what's the line the error occurs in?

**Comment by verlok** [comment]
Yes, line 91
parent.insertBefore(style, link);

I'll put it online in some minute so you can check.

**Comment by verlok** [comment]
Ok, that's where you can check it:

Not minified
http://www.andreaverlicchi.eu/?prefixfree=enable

Minified
http://www.andreaverlicchi.eu/?prefixfree=enable,minify

I hope this helps!

**Comment by LeaVerou** [comment]
Yup, after the 3rd attempt, it looks fixed now. Closing issue :)
