### ISSUE TITLE
Images loaded twice when CSS is on different domain

### ISSUE THREAD

**Issue by MarkVaughn** [LeaVerou/prefixfree#130]
When using a static domain for serving the CSS on http://www.skimbl.com/ after prefixfree is done processing the CSS the image is loaded twice.

![Developer Tools - http___www skimbl](https://f.cloud.github.com/assets/39970/10088/fb06e11a-44ed-11e2-8eca-7e10e4ab75f9.jpg)

Open the Net panel on chrome or FF.
first the CSS loads from static.skimbl.com, then the images load from static.skimbl.com. 
Then prefixfree grabs the CSS from static.skimbl.com and then loads the images from www.skimbl.com

the only way I can fix this is putting in absolute rather than relative paths but the set up for the developers and servers requires the flexibility of relative paths.

**Comment by MarkVaughn** [comment]
duplicate of #62

**Comment by LeaVerou** [comment]
I’m sorry, how is it a duplicate of #62? They look like completely different bugs to me. 

Also, judging from that screenshot, the image is NOT loaded twice. The 2nd request is a 304, i.e. the image still loads from cache. That said, it seems really stupid that the browser would send another request. Looks like a browser issue to me, not much -prefix-free can do about that.

**Comment by LeaVerou** [comment]
Oooooh, I see it now. It sends 2 requests, because the URL is different! @SimonSapin, does your patch solve this?

**Comment by SimonSapin** [comment]
I guess it should, but I don’t see the images being loaded twice on http://www.skimbl.com/ right now.

**Comment by LeaVerou** [comment]
You mean skimbl.com is using the patch already? I’m confused.

(sorry, just woke up, haven’t had coffee yet :)

**Comment by SimonSapin** [comment]
Looks like it: https://github.com/LeaVerou/prefixfree/pull/129#issuecomment-11324401

**Comment by MarkVaughn** [comment]
Yep, used the patch
