### ISSUE TITLE
Add support for :placeholder

### ISSUE THREAD

**Issue by ghost** [LeaVerou/prefixfree#140]
Probably low-priority, but `:placeholder` aliasing `::-webkit-input-placeholder` and `:-moz-placeholder` would be _awesome_.

:smile:

**Comment by LeaVerou** [comment]
One of -prefix-free’s goals is to make the distinction easier between proprietary code and experimental standards. :placeholder is still proprietary. Once it's included even in an ED, I will add it. Though -prefix-free only prefixes, it doesn't change stuff so it wouldn't work in this case. It's pretty easy to write a plugin that does this though. ;)
