### ISSUE TITLE
background-image: linear-gradient not working?

### ISSUE THREAD

**Issue by josefrichter** [LeaVerou/prefixfree#142]
I have exactly this line

background-image: linear-gradient(bottom, #ff8b01 0%, #ffb547 100%), linear-gradient(bottom, #ff8b01 0%, #ffb547 100%);

and it doesn't get processed to -webkit-linear-gradient stuff.

Is that a bug?

**Comment by LeaVerou** [comment]
Does the gradient show?

**Comment by josefrichter** [comment]
No it doesn't. Very latest Chrome on Mac. It works when I manually use -webkit prefixed gradients.

**Comment by LeaVerou** [comment]
Oh, I see what happened. Chrome unprefixed gradients, but its using the newer syntax, which requires keywords like `to top` instead of `bottom`. Use both versions along, unprefixed, and it will work everywhere. :)
For example:

``` css
background-image: linear-gradient(bottom, #ff8b01 0%, #ffb547 100%), linear-gradient(bottom, #ff8b01 0%, #ffb547 100%);
background-image: linear-gradient(to top, #ff8b01 0%, #ffb547 100%), linear-gradient(to top, #ff8b01 0%, #ffb547 100%);
```

**Comment by josefrichter** [comment]
thanks a lot!
