### ISSUE TITLE
Opera says it's switching to Webkit.

### ISSUE THREAD

**Issue by ilessy** [LeaVerou/prefixfree#144]
http://my.opera.com/ODIN/blog/300-million-users-and-move-to-webkit
Is it to say in the near future we don't have to write "-o-" prefix anymore?

**Comment by LeaVerou** [comment]
Depends on how you define "near future", but yeah, eventually. Not sure how this is a -prefix-free issue though, when using -prefix-free you don't have to use -o- anyway :P
