### ISSUE TITLE
stopped working on Chrome 26.0.1410.43

### ISSUE THREAD

**Issue by haggen** [LeaVerou/prefixfree#151]
I was working on my Mac, with Chrome, and everything was OK. Then I turned on my PC and fired my site, also on Chrome. Immediately I noticed linear-gradients stopped working. After further investigation I realized that the CSS files were being parsed but no property was actually being prefixed.

Then I checked both browser (on Mac and on PC) versions. Chrome on Mac was outdated (24) and on PC it was up to date (26).

Simply updated my Chrome on my Mac and the same error (no prefixes) occurred.

I assume Prefixfree is not working under Chrome 26.

**Comment by LeaVerou** [comment]
This is odd. The -prefix-free website (which uses prefixfree) looks like it’s prefixed just fine http://leaverou.github.com/prefixfree/

**Comment by haggen** [comment]
Crap, I forgot to run such a simple check. I'll investigate further, but currently:
- I'm working w/ a brand new Rails application;
- There's no other JavaScript being loaded;
- I'm using Anvil (Pow!) to start the server;

Any clues ?

**Comment by LeaVerou** [comment]
Any JS errors?

**Comment by haggen** [comment]
None, there's only the log of the CSS being requested (xhr finished loading).

**Comment by LeaVerou** [comment]
Are you sure it’s not a cross-origin issue?

**Comment by haggen** [comment]
The XHR requests are listed as successful (304). The `<style>` is added with the actual content of the CSS files. Does it still could had cross-origin issues ?

Btw, I just tried to remove everything else from CSS but the linear-gradient it self. Also dropped the usage of the background shorthand in favor of background-image. Still not working.

**Comment by LeaVerou** [comment]
No, it’s not a cross origin issue then. Do you mind mailing me a URL to a (as small as possible) testcase where you can reproduce the bug? Thanks!

**Comment by haggen** [comment]
Don't mind at all, since you're being so kind to answer so quickly. :) Gimme 5 minutes.

**Comment by haggen** [comment]
http://jsfiddle.net/G2uCA/ doesn't work.

**Comment by LeaVerou** [comment]
Thanks, but a jsfiddle won't do I’m afraid. :( There have been many instances of -prefix-free not working in jsfiddle for some reason, even though it worked fine on the actual HTML page (no idea why). Would it be too much if I asked you to upload a regular HTML page? Sorry!

**Comment by haggen** [comment]
I was searching around and I just found out the problem. You wrote this: http://lea.verou.me/2012/07/important-prefix-free-update/

Going to the fiddle I linked above and changing the syntax from `top` to `to bottom` make it work again.

As you can see: http://jsfiddle.net/G2uCA/1/

I know, I should feel bad about this. I do. :/

**Comment by LeaVerou** [comment]
No worries, it happens to a lot of people. :)
