### ISSUE TITLE
Where should I include prefixfree.min.js?

### ISSUE THREAD

**Issue by liorocks** [LeaVerou/prefixfree#154]
@LeaVerou 

Where should I include the downloaded js file?
Before I load stylesheets? After them ?
Or it doesn't matter ?
Thanks!

**Comment by mkantor** [comment]
Check out [the "How to use" section on the -prefix-free homepage](http://leaverou.github.io/prefixfree/#howto).

**Comment by liorocks** [comment]
Ouh!
Thanks  @mkantor!
