### ISSUE TITLE
Debug mode

### ISSUE THREAD

**Issue by yukulele** [LeaVerou/prefixfree#156]
Is their a way to now how many property have been prefixed?

In some case it's hard to now if prefix-free is really needed for my css.
for example if it's only used for 2 transition on webkit, it's probably better to prefix manually but their is now way to know what prefix-free have do (even compare css file and prefix-free output with text comparator...).

**Comment by RiZKiT** [comment]
You can use the following table for that: http://caniuse.com/#cats=CSS&sort=alpha&agents=All 

Take note of the filters on the left and the **"all"** link at the end of the list.
