### ISSUE TITLE
Bower is complaining

### ISSUE THREAD

**Issue by jarrodpayne** [LeaVerou/prefixfree#165]
Bower is complaining that you have no master branch in this repo.

```
bower prefix-free#* ENORESTARGET Tag/branch master does not exist

Additional error details:
No tags found in git://github.com/LeaVerou/prefixfree.git
Available branches: gh-pages
```

Thought you'd like to know. Maybe I'm doing something wrong??

**Comment by LeaVerou** [comment]
No, you’re not doing anything wrong. Bower is. There is no reason to name my main branch master apart from it being the default and I’m not going to change my workflow for Bower. Naming it gh-pages allows me to push to every commit to Github Pages with no extra effort.

**Comment by jarrodpayne** [comment]
Ah after reading https://github.com/bower/bower/issues/107 and https://github.com/bower/bower/issues/8 it doesn't seem to be a gh-pages problem. The real problem seems to be repos that don't use tagging. Oh well, I can manage this dependency separately.

**Comment by viniciuspires** [comment]
I also had the same problem.
Maybe tagging stable versions would solve this... Is that possible?

**Comment by konsumer** [comment]
Yep, bower requires tagging. It's a good idea for versioned code, anyway.
