### ISSUE TITLE
float bug in chrome

### ISSUE THREAD

**Issue by Mantish** [LeaVerou/prefixfree#170]
There seems to be a bug when there's an inline (or inline-block) element followed by a floated element:

http://cdpn.io/bryak

It works fine in firebug, but in chrome the second element doesn't float.
It's really odd since there are no properties that need to be prefixed

**Comment by TylerEich** [comment]
This feels like an issue for the [Chromium project](https://code.google.com/p/chromium/issues/list), as prefix-free has no bearing on these properties or how the browser renders them.

As a side note, the proper float behavior is seen in the Chrome 32.0.1651.2 canary, so a fix may already be on its way.

**Comment by Mantish** [comment]
Well, the thing is that the bug is triggered only when prefixfree is included...i guess we'll have to wait and see

**Comment by Yeswanth-JG** [comment]
@TylerEich 
Actually, there is some conflicts with the canary.

As canary is just experimental. Chromium based browsers (opera -next & chrome) are not rendering the things with third party plugins..

For reference, you can check the below issue. #183

**Comment by Mantish** [comment]
I just tested again and the issue seems to be solved in chrome 31 so I'm gonna close it.

**Comment by TylerEich** [comment]
@Yeswanth-JG

I tested [the original codepen](http://codepen.io/Mantish/full/bryak) on Mac OS X 10.9.1 (13B42) in the following browsers:
- Safari v7.0.1 (9537.73.11)
- Google Chrome v32.0.1700.107 (1700.107)
- Google Chrome Canary v34.0.1840.0 (1840.0)
- Firefox v26.0 (2613.12.5)
- Firefox Aurora v29.0a2 (2914.2.8)

All results are identical, and all are expected. I didn't see any bugs in the rendering.

Prefixfree was not included in the codepen. Are you talking about a conflict with prefixfree and Chromium?

**Comment by Yeswanth-JG** [comment]
@TylerEich 
Ya..! The problem is with the support to third party from Canary engine..! :)
