### ISSUE TITLE
Doesn't fix for "break-inside"

### ISSUE THREAD

**Issue by JacobDB** [LeaVerou/prefixfree#175]
IE10+ uses "break-inside" instead of "column-break-inside," but this script doesn't correct for that.

**Comment by LeaVerou** [comment]
Are you sure IE10 requires `break-inside` to be prefixed? This script doesn't have a list of properties, it gets them from the browser, so this seems highly unlikely.

**Comment by JacobDB** [comment]
It's not that it needs prefixed, it's that I have to use two different properties. So instead of just using break-inside or column-break-inside, I have to include both. I guess this might be outside the scope of your script, but I figured I'd mention it.

**Comment by LeaVerou** [comment]
Yes, that is outside the scope of -prefix-free. But thanks anyway!
