### ISSUE TITLE
Variable plugin issues

### ISSUE THREAD

**Issue by necolas** [LeaVerou/prefixfree#178]
Hey, I'm sure you're aware of this but didn't see any existing issues. There are some problems with the variable plugin (as described on the project page) when variables are not supported in the browser.
1. Variable declarations should be limited to `:root` because scoping is not supported, and not doing so introduces differences between browsers and incompatibility with the CSS spec.
2. The values of variables declared for `:root` should be determined before any replacement takes place.
3. Fallbacks are not properly supported as the regex can't handle CSS functions in the fallback value.

**Comment by LeaVerou** [comment]
Oh yeah, this plugin is a total hack and I think I explain this in its listing. It's just a starting point to show how people can use the API to build polyfills, but it's incredibly crude.
