### ISSUE TITLE
Stylesheet media type is not included

### ISSUE THREAD

**Issue by kaij** [LeaVerou/prefixfree#18]
I used this great library in a new project. However, I ran into a problem by having a media="print" stylesheet. When using prefixfree, the print stylesheet gets included without media type - which will show the print view of the page (which has completely different layout in my case).

There is a workaround by including the "@media print {}" in the print stylesheet. However, I think it is safer to carry the media type into the newly created stylesheet node. Maybe you could include this patch:

73 +:           media = link.getAttribute('media'),
97+:          if (media) { style.setAttribute('media', media); }

Regards, Kai

**Comment by LeaVerou** [comment]
Oh damn, I kept reminding myself to add this and I forgot. Will fix today.

**Comment by LeaVerou** [comment]
Fixed?

**Comment by kaij** [comment]
Wow, that was fast :-)

Yes, now it's working as expected! Thanks for including!

Although, if there is no media type indicated, the attribute is now media="" (FF7). I don't know whether this will have any side-effects in some browsers (I think there should be either no attribute or a default like 'all').

**Comment by LeaVerou** [comment]
AFAIK, `media=""` is the same as `media="all"`. So, while I understand it might look ugly, if it causes no issues, I'd prefer to keep the code as short as possible. 

I'm closing this, since the fix works. If there are any issues with it, feel free to reopen. :)
