### ISSUE TITLE
background bug

### ISSUE THREAD

**Issue by michaelzhouh** [LeaVerou/prefixfree#181]
/_background:-moz-linear-gradient(top,#fff,#F6D66E);
background:-webkit-linear-gradient(top,#fff,#F6D66E);
background:-o-linear-gradient(top,#fff,#F6D66E);
background:-ms-linear-gradient(top,#fff,#F6D66E);_/
background:linear-gradient(top,#fff,#F6D66E);

if I commented the code, it doesn't work.

**Comment by LeaVerou** [comment]
Sigh.

Please read my reply on the previous issues on this (spoiler: there’s no -prefix-free bug here):
https://github.com/LeaVerou/prefixfree/issues/174
https://github.com/LeaVerou/prefixfree/issues/158
https://github.com/LeaVerou/prefixfree/issues/142
https://github.com/LeaVerou/prefixfree/issues/128
https://github.com/LeaVerou/prefixfree/issues/117
