### ISSUE TITLE
With Wordpress doesn't works

### ISSUE THREAD

**Issue by xavierartot** [LeaVerou/prefixfree#190]
Hi,
When I use prefixfree with wordpress.
I have 6 errors ?
XMLHttpRequest cannot load http://fonts.googleapis.com/css?family=Open+Sans%3A300italic%2C400italic%2C600italic%2C300%2C400%2C600&subset=latin%2Clatin-ext&ver=3.8.1. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8888' is therefore not allowed access. (index):1
2
XMLHttpRequest cannot load http://fonts.googleapis.com/css?family=Lato%3A300%2C400%2C700%2C900%2C300italic%2C400italic%2C700italic. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8888' is therefore not allowed access. (index):1
2
XMLHttpRequest cannot load http://fonts.googleapis.com/css?family=Adamina&ver=3.8.1. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8888' is therefore not allowed access. (index):1
event.returnValue is deprecated. Please use the standard event.preventDefault() instead. jquery.js?ver=1.10.2:4
Resource interpreted as Script but transferred with MIME type text/html: "http://www.superfish.com/ws/sf_main.jsp?dlsource=wxpifdx&CTID=cool3_pirate&userId=OUQ1QTUxMEQtMjJGOS00Nz". VM2207:1

Thanks

**Comment by LeaVerou** [comment]
From the homepage: 

> Prefixing cross-origin linked stylesheets is not supported, unless they are CORS-enabled

This has nothing to do with Wordpress.

**Comment by xavierartot** [comment]
I will use some mixins, etc.
http://css-tricks.com/snippets/css/useful-css3-less-mixins/
