### ISSUE TITLE
refresh style

### ISSUE THREAD

**Issue by yukulele** [LeaVerou/prefixfree#192]
Is their a way to refresh all styles with PrefixFree without refresh full page?

I think to something like this:

``` javascript
PrefixFree.refreshAll();
```

To force reload all css files (via XMLHttpRequest) and apply PrefixFree (only in case of change).

**Comment by LeaVerou** [comment]
Not out of the box, but it should be pretty easy to do, as the href is maintained in the `data-href` attribute. Can't see any way to do that with inline `<style>` elements though.

**Comment by yukulele** [comment]
My real goal is to make a css auto reload supporting prefix-free.

i start it (https://github.com/yukulele/CSSrefresh) but i think i should use more PrefixFree / StyleFix internal tools.

for example, i actually can't use StyleFix relative to absolute URLs convertor.
