### ISSUE TITLE
@font-face problem

### ISSUE THREAD

**Issue by lehtu** [LeaVerou/prefixfree#193]
When I am using @font-face from google fonts via external links I am getting this in my chrome's console:

```
XMLHttpRequest cannot load http://fonts.googleapis.com/css?family=Swanky+and+Moo+Moo. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://mywebsite.com' is therefore not allowed access.
```

It seems that fonts are working, but I just don't like errors in my console :(
This same thing is happening in here: http://elrumordelaluz.github.io/csshake/

**Comment by LeaVerou** [comment]
It's because the Google Fonts stylesheet is cross-origin, so prefix-free can't process it. It works because PF doesn't need to process it. If you want to not have an error either use the `@import` method (which should be the default in Google Fonts anyway) or add a `data-noprefix` attribute to it.
