### ISSUE TITLE
Typo...?

### ISSUE THREAD

**Issue by ghost** [LeaVerou/prefixfree#195]
The following section of the prefix free script I just downloaded appears to have a typo; the pipe toward the end is wrapped with one double quote, and one single. Was this a typo or on purpose?

if(i){n=n.replace(/url(\s*?((?:"|')?)

**Comment by LeaVerou** [comment]
It's not a pipe wrapped in quotes, it’s a lookahead that matches either the single or the double quote. The pipe in regex means OR.
