### ISSUE TITLE
Object.defineProperty shim is non-spec compliant.

### ISSUE THREAD

**Issue by jdalton** [LeaVerou/prefixfree#2]
I noticed you shim [Object.defineProperty](http://es5.github.com/#x15.2.3.6), but only partially. This may cause problems w/ 3rd-party code that lazy detects functionality with checks like `if (Object.defineProperty) {`. Your own code assumes `Object.defineProperty` has functionality that the shim does not provide _(setting the `enumerable` and `configurable` descriptor attributes)_. Since the primary use of your shim is for getter/setter why not just abstract those into private util functions.

**Comment by LeaVerou** [comment]
Is there a way to shim it completely? Every shim I've seen only does it partially.

The main reason I chose to do it like that was filesize, but I guess that's not such a big difference.

**Comment by jdalton** [comment]
There isn't a way to shim it completely, _that I'm aware of_, which is why it's a good idea to not shim it at all.
