### ISSUE TITLE
body { 	perspective: 400px; }  not being prefixed in moz at least

### ISSUE THREAD

**Issue by ghost** [LeaVerou/prefixfree#20]
-moz-perspective does exist and function in latest firefox

test drive page currently will generate "-webkit-perspective", but on moz nada

thanks for a brilliant tool. very next-gen :)

**Comment by LeaVerou** [comment]
Hi, I just tested on Firefox 10 (nightly) and it works fine. Which version did you experience the issue in?

**Comment by panayiotisa** [comment]
3d transforms are not enabled in firefox 7

**Comment by ghost** [comment]
This was FF 7.01 on Mac

**Comment by LeaVerou** [comment]
The property doesn’t seem to be supported there with a prefix. Try it for yourself: Run in the console `'MozPerspective' in document.body.style`

I guess it’t not enabled in that version of Firefox, like panayiotisa said.

**Comment by ghost** [comment]
ah right you are. a little too far ahead of the curve there.
