### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by glan** [LeaVerou/prefixfree#205]
It would be cool to slot in a `package.json` file and push this up to npm.

**Comment by mciparelli** [comment]
+1

**Comment by ianobermiller** [comment]
+1

**Comment by krazyjakee** [comment]
+1

**Comment by rojaro** [comment]
+1

**Comment by crispen-smith** [comment]
Why on earth would this belong on NPM?  It's a front end only tool, I can certainly see the value of adding it to a project via bower, but that works today.

**Comment by krazyjakee** [comment]
Many people, including myself, use NPM for frontend and backend in a single package.

Thinking about it, I would perhaps prefer npm be for backend on principle, only because it's so saturated already. I guess it's down to convenience.

**Comment by crispen-smith** [comment]
NPM is a fantastic package manager, but I think you've exactly identified the reason to seperate them from each other.  And while I certainly don't want to speak to any particular architecture, as a node developer I find that using `serve-static("/bower_components")` allows me to package, serve, and manipulate all of my front-end packages without allowing someone to forcefully browse to myapp.com/js/some_vulnerable_component

**Comment by cowwoc** [comment]
@crispen-smith Tools like Browserify and Webpack bundle packages from npm for web browsers. There is a strong use-case there.

**Comment by crispen-smith** [comment]
I've never had a problem loading from github with bower, I can't speak to Browserify or Webpack, though if Webpack requires an NPM entry for loading then yes, I'll +1 this.

**Comment by cowwoc** [comment]
@crispen-smith Technically speaking any library that depends on npm that load files from github, but you lose the versioning information. The main benefit of pushing to npm would be being able to declare a dependency on a version range.

**Comment by crispen-smith** [comment]
That does make sense then,  I still feel it muddies the water between front-end and back-end package managers but I think that's a bigger issue than prefix-free.

**Comment by LeaVerou** [comment]
Are there any other scripts that require a browser environment published on npm?

**Comment by krazyjakee** [comment]
https://www.npmjs.com/package/jqueryui-browser

**Comment by luca-moser** [comment]
In case you do use Browserify and Gulp as myself, you can simply use [gulp-autoprefixer](https://www.npmjs.com/package/gulp-autoprefixer) to do the work for you instead of binding Lea's prefixfree statically into the page.

@LeaVerou there are popular scripts like jQuery and Backbone which are on NPM.

**Comment by jasonkuhrt** [comment]
I am interested in consuming the API for inline-style prefixes but stopped short because no package integration.

**Comment by ianobermiller** [comment]
You can check out Radium's [Prefixer](https://github.com/FormidableLabs/radium/blob/00c57824e54fda4cf3dd852c1db6cc2edf2a40ef/modules/prefixer.js), which was inspired by PrefixFree and css-prefix. Could be moved to its own npm module.

**Comment by jasonkuhrt** [comment]
@ianobermiller Already found https://github.com/jsstyles/css-vendor

**Comment by phun-ky** [comment]
npm package management for frontend projects are gold tbh, bower has it strengths, but not as powerfull as npm. 

I would greatly appreciate this module (and conic-gradient) to be published on npm!

+1

**Comment by ianobermiller** [comment]
You may also be interested in [`inline-style-prefixer`](https://github.com/rofrischmann/inline-style-prefixer), which has the advantage of working on the server as well.

**Comment by LeaVerou** [comment]
LOL at my earlier ignorant comment here.

Yes, this should definitely be published to npm, it's long overdue. Once my laptop is fixed (it died unexpectedly and I'm currently using my partner's to Github for a bit) it's on my to-do list.

**Comment by LeaVerou** [comment]
Done!
https://www.npmjs.com/package/prefixfree
