### ISSUE TITLE
Issue with css filenames in developer tools

### ISSUE THREAD

**Issue by Somebi** [LeaVerou/prefixfree#208]
All links become broken and not shown inside developer tools because it's placing all styles inside <style> tag. I guess because of that.

**Comment by Somebi** [comment]
http://stackoverflow.com/questions/27150499/google-chrome-developer-tools-not-showing-css-filename-next-to-css

**Comment by LeaVerou** [comment]
Unfortunately there’s no way to do what prefixfree does with today’s web technologies without inlining the CSS. However, the filename is added as a `data-href` attribute on the `<style>` tag. 
![screen shot 2014-11-27 at 16 43 51](https://cloud.githubusercontent.com/assets/175836/5221909/a63bbb02-7654-11e4-891f-7e5ef65edbc4.png)
