### ISSUE TITLE
prefixfree generates errors when viewing a local file

### ISSUE THREAD

**Issue by jessamynsmith** [LeaVerou/prefixfree#213]
When viewing files locally that use prefixfree, I see errors similar to the following:
XMLHttpRequest cannot load file:///Users/jessamyn/Development/llc-intro-to-jquery/framework/css/theme-llc.css. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.

I recognize that I can work around this by specifying data-noprefix but I would prefer not to have to do so.

**Comment by LeaVerou** [comment]
FAQ, third question. http://leaverou.github.io/prefixfree/#faq
