### ISSUE TITLE
prefixing keyframe animation on IE10 issue

### ISSUE THREAD

**Issue by Jojaba** [LeaVerou/prefixfree#25]
When -prefix-free adds the -ms- prefix to keyframe animation, animation doesn't work. Not sure that this is a -prefix-free issue, because when disabling -prefix-free, no animation doesn't work either. Maybe the tested version is not uptodate !!! (10.0.8102.0)

Go to this site to see this issue: http://jojaba.free.fr/alsacreations/prefixfree-demo/prefixfree-demo.html

**Comment by LeaVerou** [comment]
Closing this issue since it doesn't work in general, even without -prefix-free. Feel free to reopen if you get your hands on an IE10 that supports animations and they break with -prefix-free. :)
