### ISSUE TITLE
Doesn't seem to work on mobile devices

### ISSUE THREAD

**Issue by muzair** [LeaVerou/prefixfree#27]
I checked on iOS and android and the js doesn't seem to work on mobile devices. Can you please take a look and suggest a workaround?

Great work btw and many thanks for all the hard work.

**Comment by LeaVerou** [comment]
That's odd, I've checked it myself on my iPhone and it worked fine.

Could you please let me know about:
- versions you tested
- what exactly do you mean by "doesn't work"?

**Comment by nverba** [comment]
I had a quick look at this on my Samsung Galaxy S2, Android 2.3.3

Firefox displays everything correctly. 

The stock browser and Dolphin browser both have issues with border-radius and text shadows, in that they just don't render, also they don't render the logo.svg

**Comment by muzair** [comment]
Thanks for the quick reply. Here is a screenshot of the prefix-free home page from my nook color running android. You can see that rounded corners aren't working but css transitions seem to be working fine. I will test again on iOS tomorrow using the latest version in my project and will get you the links.

 http://db.tt/iVUtAefg

**Comment by muzair** [comment]
Some more screenshots of android browsers. They seem to be rendering just fine. 
FF-http://db.tt/1ZEaBytM
Opera- http://db.tt/AgcskmDa

**Comment by muzair** [comment]
iPad(5.0.1) Screenshots
http://dl.dropbox.com/u/6961669/photo%201.PNG
http://dl.dropbox.com/u/6961669/photo%202.PNG
http://dl.dropbox.com/u/6961669/photo%203.PNG

iPod(4.3.3) Screenshot
http://dl.dropbox.com/u/6961669/photo%204.PNG

**Comment by LeaVerou** [comment]
Keep in mind that -prefix-free is not a polyfill. If a feature isn't supported at all, with or without a prefix, it's not a bug. It's only a -prefix-free bug if the feature is supported only with a prefix and -prefix-free doesn't add it.

That said, do the features that don't work fall in this category?

**Comment by muzair** [comment]
Well, it seems that you are right. 

I made a small test bed using gradients, rounded corners, text shadows and drop shadows. I only checked on android. Rounded corners and box-shadows are rendering fine but gradients and text shadows are not working in both the cases.

With prefix-free--
http://cosmive.com/prefixfree/test1.html

Without prefix-free--
http://cosmive.com/prefixfree/test2.html

It still doesn't explain rounded corners not working in android for prefix-free site. I think that android doesn't like border-radius in %.

Once again, thanks a lot for your help and all the great work.

**Comment by LeaVerou** [comment]
That's quite possible, old Webkit has such an issue and Android uses old Webkit AFAIK. Same goes for gradients, old Webkit only supports -webkit-gradient, which -prefix-free doesn't and shouldn't prefix (as it's proprietary. The whole idea of -prefix-free is enabling you to write standards-compliant CSS).

Thanks for your effort in doing all this testing! Very appreciated.
