### ISSUE TITLE
Functions don't get prefixed when they are immediately preceded by a comma

### ISSUE THREAD

**Issue by joesavage** [LeaVerou/prefixfree#28]
I recently tried to use -prefix-free on my site, but ended up dumping it as it changed code with multiple linear gradients (which I happened to get from the CSS3 Pattern Gallery) and incorrectly added vendor prefixes to each item in the gradient list instead of putting in different background-image properties. So something like this:

```
    background-image: 
            -webkit-linear-gradient(#fff 2px, transparent 2px),
            -webkit-linear-gradient(0, #fff 2px, transparent 2px),
            -webkit-linear-gradient(rgba(255,255,255,0.3) 1px, transparent 1px),
            -webkit-linear-gradient(0, rgba(255,255,255,0.3) 1px, transparent 1px);
```

SHOULD have turned into this (but didn't - it instead turned into one very long list of linear gradients [which breaks the effect in all the browsers I tried]):

```
    background-image: 
            -webkit-linear-gradient(#fff 2px, transparent 2px),
            -webkit-linear-gradient(0, #fff 2px, transparent 2px),
            -webkit-linear-gradient(rgba(255,255,255,0.3) 1px, transparent 1px),
            -webkit-linear-gradient(0, rgba(255,255,255,0.3) 1px, transparent 1px);
    background-image: 
            -moz-linear-gradient(#fff 2px, transparent 2px),
            -moz-linear-gradient(0, #fff 2px, transparent 2px),
            -moz-linear-gradient(rgba(255,255,255,0.3) 1px, transparent 1px),
            -moz-linear-gradient(0, rgba(255,255,255,0.3) 1px, transparent 1px);
    background-image: 
            -ms-linear-gradient(#fff 2px, transparent 2px),
            -ms-linear-gradient(0, #fff 2px, transparent 2px),
            -ms-linear-gradient(rgba(255,255,255,0.3) 1px, transparent 1px),
            -ms-linear-gradient(0, rgba(255,255,255,0.3) 1px, transparent 1px);
    background-image: 
            -o-linear-gradient(#fff 2px, transparent 2px),
            -o-linear-gradient(0, #fff 2px, transparent 2px),
            -o-linear-gradient(rgba(255,255,255,0.3) 1px, transparent 1px),
            -o-linear-gradient(0, rgba(255,255,255,0.3) 1px, transparent 1px);
    background-image: 
            linear-gradient(#fff 2px, transparent 2px),
            linear-gradient(0, #fff 2px, transparent 2px),
            linear-gradient(rgba(255,255,255,0.3) 1px, transparent 1px),
            linear-gradient(0, rgba(255,255,255,0.3) 1px, transparent 1px);
```

**Comment by LeaVerou** [comment]
I'm confused as to what the "very long list of gradients" looked like, could you post an example please?
I've used -prefix-free for multiple gradients many times without any problems. In fact, it's the script powering my patterns gallery, so if you got the pattern from there and it worked there, you must've done something wrong.

**Comment by joesavage** [comment]
I had it in minified CSS so maybe it was an issue with that?
It was on my live website, so I very swiftly fixed it by using manual prefixes - I'll try and get a test case set up tommorow (It's 22:18 in the UK right now) and will report back with a link when done.
If I can't re-create the problem - then it was obviously some weird one off thing, I'll wreck my production site a little for the good of -prefix-free :)

**Comment by LeaVerou** [comment]
Thank you!
Minified CSS is an area where -prefix-free hasn't been extensively tested so I'd welcome such testing very much.

**Comment by joesavage** [comment]
I've had a little bit of a further look at it, and the problem is not having the spaces after the commas that separate the "linear-gradient"s.

I've put up a test case that perfectly demonstrates the problem, here: http://test.dev-hq.net/test-cases/-prefix-free/MultipleMinifiedGradients/

**Comment by LeaVerou** [comment]
Marked as confirmed and changed the title to reflect the actual problem. Will post a patch soon.

Thank you for helping make -prefix-free better!

**Comment by LeaVerou** [comment]
Should be fixed now.
