### ISSUE TITLE
Some issues regarding gradients in Opera and iOS

### ISSUE THREAD

**Issue by lordfpx** [LeaVerou/prefixfree#29]
Hello,

I was planning to develop a PHP script in order to get rid of prefixes... and I found out you made a great js script :-). Thanks a lot for this !

So here are some difficults/bug I found :-p. the gradient property doesn't seem to work on the Opera browser, such as :

background : linear-gradient(left, #484848 0%,#a3a3a3 100%);

For the iOS device, the problem is different since the property hasn't the same format, so I guess I have to add it manually in my style sheet, isn't it ?

Thank you :-)

**Comment by LeaVerou** [comment]
Hi,

I just loaded the project's page (which uses plenty of gradients) in Opera and it works fine. I've also tested on Opera Mobile and it works fine there too. Could it be that you were testing locally? If so, please read this FAQ item: http://leaverou.github.com/prefixfree/#local-xhr

The Mobile Safari included in iOS5 natively supports `linear-gradient()` (with a prefix of course, but -prefix-free will help with that ;). If you want to support older Mobile Safaris, yes, you will have to manually include a `-webkit-gradient()` version. -prefix-free won't interfere with it. You can use this tool to generate the -webkit-gradient(): http://lea.verou.me/demos/cssgradientsplease/
In general, -prefix-free won't mess with preprefixed stuff.

By the way, in the future please open separate reports per issue. It's hard to manage issues if there are multiple on the same report.

**Comment by lordfpx** [comment]
Opera updated itself and now it works... strange, maybe my previous version was not css3 compatible for gradient.

Thanks for your online generator :-).

Ok next time I will.
