### ISSUE TITLE
DOMAttrModified not supported by WebKit

### ISSUE THREAD

**Issue by jdalton** [LeaVerou/prefixfree#3]
Just a heads up. I know that [in the past](https://github.com/dperini/nwmatcher/blob/master/src/modules/nwmatcher-cache.js#L151) the DOMAttrModified event has been buggy/not supported in all browsers that implement other Mutation events.

**Comment by jdalton** [comment]
The [WebKit bug report](https://bugs.webkit.org/show_bug.cgi?id=8191) for lack of the DOMAttrModified event _(Lacking in Safari/Chrome)_ and a [simple test case](https://bug-8191-attachments.webkit.org/attachment.cgi?id=42616).

**Comment by LeaVerou** [comment]
Hmm, you're right. Strange, I could've sworn it works in Webkit.

Maybe I should remove mutation events alltogether, too many issues, slugishness, extra code and for little reason.

**Comment by jdalton** [comment]
Mutation events get bad press because they seem to disable browser optimizations. The x-browser implementation issue is icing on the cake.

It's tricky to find a situation to use mutation events safely. I know [NWMatcher](https://github.com/dperini/nwmatcher) uses them to invalidate its selector result cache, when mutation events are available and usable. The way [NWMatcher uses it](https://github.com/dperini/nwmatcher/blob/master/src/modules/nwmatcher-cache.js) avoids the brunt of the slowdown associated with them because the listener is removed/cache-invalidated once an element is inserted/attr-changed and then added again only on the next DOM query call.

**Comment by LeaVerou** [comment]
I'm pondering removing mutation events completely from prefixfree. It would probably make it 4KB instead of 5KB, and I'm not sure how many people need them. 
If only github had polls... :(

**Comment by LeaVerou** [comment]
Mutation events were split to a separate plugin (Dynamic DOM plugin) which includes a warning about this not working in Webkit and the general slowness attributed to mutation events. So, closing issue.

**Comment by verlok** [comment]
You can start a poll elsewhere and add a link, so I could vote for removing them from prefixfree.
Can you move mutation events to a plugin, so developers can use it only if they require it?

**Comment by LeaVerou** [comment]
Um, I already did :P
Read my comment above :)

**Comment by verlok** [comment]
Damn, I got late by 11 minutes :)
