### ISSUE TITLE
PrefixFree breaks on pages that reference non-existent stylesheets

### ISSUE THREAD

**Issue by daGUY** [LeaVerou/prefixfree#30]
I discovered a very odd issue with PrefixFree while developing a site recently. On only certain pages of my site, when the script was present, an _additional_ set of styles would get loaded that conflicted with the rest of the styles on the page and completely messed up the layout.

By diffing pages that worked fine with PrefixFree against those that didn't, I discovered that all the pages that weren't working were referencing stylesheets that no longer existed. In other words, on a broken page, I would have something like `<link rel="stylesheet" href="css/template.css" />`, but nothing called `template.css` in the `css` directory. Upon removing these references, the pages immediately began rendering correctly again.

The strangest part is that I couldn't determine where those additional styles were coming from. I copied them out of Firebug and searched for them across my entire project, and found nothing that was defining them anywhere. The only thing I could think of was that PrefixFree was acting on cached versions of the stylesheets that no longer existed - but I looked at old versions from before they had been removed, and nothing inside them matched the additional styles I was seeing through Firebug.

I'm not sure if there's anything you can or should do to PrefixFree to address this, since the solution for me was to remove references to non-existent stylesheets - which is good practice anyway - but I wanted to bring it up since it did severely alter the layout/presentation of my pages.

**Comment by LeaVerou** [comment]
That's really odd. Do you have an example of these styles that were added?

**Comment by daGUY** [comment]
Below are the exact styles that are added. I have to think they're coming from my project somewhere since I don't understand how or why PrefixFree would be creating them, but as I said I can't find them anywhere (and because PrefixFree seems to insert styles inline after processing them, I can't use Firebug to trace which file they're coming from).

So really there's two different but related issues here: (1) Why does PrefixFree load additional styles when the page references non-existent stylesheets? (2) Where are these additional styles coming from? But if you can fix (1) then that basically makes (2) irrelevant.

fieldset {
    padding: 0 15px 10px;
}
h1 {
    color: #FFFFFF;
    font-size: 2.4em;
    margin: 0;
}
h2 {
    color: #CC0000;
    font-size: 1.7em;
    margin: 0;
}
h3 {
    color: #000000;
    font-size: 1.2em;
    margin: 10px 0 0;
}
#header {
    background-color: #555555;
    color: #FFFFFF;
    font-family: "trebuchet MS",Verdana,sans-serif;
    margin: 0;
    padding: 6px 2%;
    width: 96%;
}
#content {
    margin: 0 0 0 2%;
    position: relative;
}
.content-container {
    background: none repeat scroll 0 0 #FFFFFF;
    margin-top: 8px;
    padding: 10px;
    position: relative;
    width: 96%;
}

**Comment by LeaVerou** [comment]
You _can_ use Firebug to trace them, as a data-href attribute gets added to the generated &lt;style> element.

These styles don't remind me of anything, so they must be coming from your project. Maybe a cached stylesheet? XHR uses the cache normally after all.

In any case, could you make a simplified testcase with the issue and upload it somewhere? It would help a lot.

**Comment by daGUY** [comment]
I wasn't aware of the data-href attribute - thanks to that, I figured it out! When the page requests the nonexistent stylesheets, my server returns a 404 page for each one. PrefixFree thinks these 404 pages are the stylesheets that were requested and inserts them onto the page between `<style>` tags, just like it does with the other stylesheets. On the 404 page itself, there's a `<style>` tag in the `<head>`, and _that's_ where those extra styles are coming from.

**Comment by LeaVerou** [comment]
Wow, that's actually a bug, as I assume such 404 errors will be returned by many hosts. Will try to address it sometime in the next couple of days. Thanks for reporting!

**Comment by LeaVerou** [comment]
Better late than never, as they say :)

Is it fixed?
