### ISSUE TITLE
Any chance you would add background-clip?

### ISSUE THREAD

**Issue by joelpittet** [LeaVerou/prefixfree#33]
-moz-background-clip: padding; 
-webkit-background-clip: padding-box; 
background-clip: padding-box;

**Comment by LeaVerou** [comment]
It should work already, just won't compensate for the different kinds of values. So you should do:

```
background-clip: padding;
background-clip: padding-box;
```

**Comment by joelpittet** [comment]
I was just trying it in the Test Drive and wasn't having any luck seeing the -webkit prefix for safari or -moz for firefox.

**Comment by LeaVerou** [comment]
I think you've fundamentally misunderstood how -prefix-free works. It doesn't add all prefixes, it only adds the current browser's prefix, only when a property/value/etc needs it to work (=when a prefix-less version isn't supported).

Given that background-clip is supported without a prefix in most modern browsers, you won't see a difference in that.

**Comment by joelpittet** [comment]
Ah I see sorry
