### ISSUE TITLE
Add support for CSS3 PIE -pie- prefixes?

### ISSUE THREAD

**Issue by daGUY** [LeaVerou/prefixfree#34]
This is probably a long shot, but would you consider having PrefixFree generate -pie- prefixed properties for use with CSS3 PIE?

In other words, it would be awesome if I could write this in my stylesheet:

<code>body {background: linear-gradient(#fff, #000);}</code>

And have PrefixFree generate this in IE:

<code>body {-pie-background: linear-gradient(#fff, #000);}</code>

Then I could drop in PIE.htc and my non-prefixed CSS3 gradients would work in all versions of IE down to 6! I know it's probably out of the scope of PrefixFree, but maybe it could be offered as a plugin?

**Comment by LeaVerou** [comment]
This has been requested before, but it's impossible with the current -prefix-free architecture, for a number of different reasons:
- There's nothing to detect, as it's not a real prefix
- IE9 still needs prefixes for _some_ things, so you'd end up having 2 prefixes
- Some properties are prefixed conditionally in PIE. For example, `background` may or may not be prefixed, depending on its value. So, PF would have to parse the CSS, you can't get away with a few substitutions like now.

So no, sorry. Way too much work, for not that huge benefit.
