### ISSUE TITLE
Gradient not working on my Android 2.3.6

### ISSUE THREAD

**Issue by jitendravyas** [LeaVerou/prefixfree#36]
Android 2.3.6 default browser not showing gradient while other browser are fine. I have only tested in Android 2.3.6 version.

.discount-label {
                                     left: -7.1em;
                                     top: 1.4em;
                                     background: url(../img/texturee.png), linear-gradient(left, #de2785 1%,#f954b1 50%,#de2785 100%);}

it's working in all but not android. For me now only option to add vendor-prefixes to whole css. I had made it for a big project.

**Comment by LeaVerou** [comment]
If you manually add the prefixes instead of using prefixfree, does it work?

**Comment by jitendravyas** [comment]
Yes if i add this manually
-webkit-gradient(linear, left top, left bottom, color-stop(1%,#de2785),
color-stop(50%,#f954b1), color-stop(100%,#de2785))

then it works. I would be happy if you fix this soon. it will save my time

## because I have used lots of gradients in current project.

Jitendra Vyas
Senior Front End Developer

http://skarp.dk

---

Skype : jitendra.web I Twitter @jitendravyas I Linkedin:
http://linkd.in/jitendra I
 Google Plus - gplus.to/jitendra I Read my Blog at http://j.mp/vyasblog

On Mon, Jan 16, 2012 at 10:32 PM, Lea Verou <
reply@reply.github.com

**Comment by LeaVerou** [comment]
-webkit-gradient() is NOT the same as -webkit-linear-gradient(). It has entirely different syntax. -prefix-free doesn't do any kind of transformation, it just adds the prefix if it's needed. If Android doesn't support -webkit-linear-gradient yet, you will need to add -webkit-gradient() manually.

**Comment by jitendravyas** [comment]
OK do you know tool where I convert this type code

 linear-gradient(left, #de2785 1%,#f954b1 50%,#de2785 100%);

into this -webkit-gradient(linear, left top, left bottom,
color-stop(1%,#de2785), color-stop(50%,#f954b1), color-stop(100%,#de2785))

## I have multiple gradients.

Jitendra Vyas
Senior Front End Developer

http://skarp.dk

---

Skype : jitendra.web I Twitter @jitendravyas I Linkedin:
http://linkd.in/jitendra I
 Google Plus - gplus.to/jitendra I Read my Blog at http://j.mp/vyasblog

On Mon, Jan 16, 2012 at 10:46 PM, Lea Verou <
reply@reply.github.com

**Comment by LeaVerou** [comment]
http://lea.verou.me/demos/cssgradientsplease/ does that too (make sure not to include the trailing semicolon or it won't work)

**Comment by jitendravyas** [comment]
## Thanks. Nice time/life saver tool :)

Jitendra Vyas
Senior Front End Developer

http://skarp.dk

---

Skype : jitendra.web I Twitter @jitendravyas I Linkedin:
http://linkd.in/jitendra I
 Google Plus - gplus.to/jitendra I Read my Blog at http://j.mp/vyasblog

On Mon, Jan 16, 2012 at 10:54 PM, Lea Verou <
reply@reply.github.com

**Comment by chrisjul** [comment]
thanks LeaVerou for ur  valuable code   and tool
