### ISSUE TITLE
Relative URLs do not work

### ISSUE THREAD

**Issue by ross999** [LeaVerou/prefixfree#4]
Tried out this script today and as soon as I refreshed the page I was working on all of the css background images disappeared as soon as the script loaded. I tried the script first at bottom of page, where I normally put js like this, tried it in the <head> as well.

I'm on a mac and this bug happened in Chrome 14 and the latest Firefox version 7.0.

I typically write my css on one line and write background properties like this: background: url(../img/hero-bg.png) no-repeat;

Would love to use the script but unfortunately won't be able to with this bug.

Thanks

**Comment by LeaVerou** [comment]
Can you please provide a testcase?

**Comment by LeaVerou** [comment]
Can you please make a small testcase in which the problem is still reproducible?
http://jsfiddle.net/ might help with it.

If you can't let's talk on Skype, but it would really be easier for me if you could.

**Comment by ross999** [comment]
Ok - Just created a test case.

This is how it looks normally, without prefixfree js: http://minus.com/mXBHYlVAu#1f

This is what it looks like with script enabled: http://minus.com/mH7QZ2sZk#1f

And a link to the html: 'removed by dross202'

Also just noticed it's making the @font-face not work.

Hope this helps,
David

**Comment by LeaVerou** [comment]
Sorry, I wasn't online before :(

Your testcase gives me a 403 error :(

**Comment by ross999** [comment]
You online now? I'll just zip it up and send to you via skype or email.

**Comment by LeaVerou** [comment]
Turns out the problem is that because CSS files get embedded in the document, if the CSS files reside in a different directory than the HTML, the relative URLs stop working. I need to fix this by rewriting the relative URLs. Hopefully tomorrow.

Also: Edited the issue title.

**Comment by LeaVerou** [comment]
David (and everyone else that had an issue), can you please test if it's working now?

**Comment by ross999** [comment]
Seems to be working great now. Thanks!

**Comment by LeaVerou** [comment]
Yay!
