### ISSUE TITLE
linear-gradients don't get prefixed

### ISSUE THREAD

**Issue by brianfreud** [LeaVerou/prefixfree#42]
For linear-gradient and the others, where the prefix is in the value, not the attribute, prefixfree's not doing anything.

```
background: linear-gradient(top,#d6f0fc 0,#ffffff 50%,#3867a1);
```

should be adding:

```
background: -moz-linear-gradient(top,#d6f0fc 0,#ffffff 50%,#3867a1);
background: -ms-linear-gradient(top,#d6f0fc 0,#ffffff 50%,#3867a1);
background: -o-linear-gradient(top,#d6f0fc 0,#ffffff 50%,#3867a1);
background: -webkit-gradient(linear, 0 0, 0 100%, from(#d6f0fc), color-stop(0.5, #ffffff), to(#3867a1));
background: -webkit-linear-gradient(top,#d6f0fc 0,#ffffff 50%,#3867a1);
```

but it's not.

Hopefully there's a fix; gradients are the biggest part of my css; if I can trim them out, the size savings from that alone would make prefixfree worthwhile, even ignoring all the other prefix headaches that it saves me!  :D

**Comment by LeaVerou** [comment]
It shouldn't be adding any of that, it only adds the prefix before linear-gradient(). -prefix-free is not a preprocessor.

That said, gradients should work (the test page has plenty of them). Do you have an example that demonstrates the issue? Which browser does it happen in?

**Comment by brianfreud** [comment]
I was testing in Chrome 17.0.942.0 dev, FF nightly 11, and Opera, all on Ubuntu.  With just the "background: linear-gradient" in the css, I was ending up with a blank white background in each, rather than gradients.

**Comment by LeaVerou** [comment]
You must be doing something wrong, I've been using -prefix-free for gradients since time immemorial. Could I please see an online testcase?

**Comment by brianfreud** [comment]
Sure.  http://jsfiddle.net/wzbhG/1/ includes the prefixed gradients, and it works.  http://jsfiddle.net/WAqKw/2/ , identical except that the prefixed gradients have been removed; there is no gradient, nor is one being added by the script.

**Comment by LeaVerou** [comment]
Works by including the resource separately http://jsfiddle.net/leaverou/WAqKw/3/
So it had something to do with the way you pasted the code in the script pane. My guess is the malformed script tags (e.g. `< script >`) you included, which weren't even needed and probably caused parse errors.

**Comment by brianfreud** [comment]
< script > actually came from their TidyUp thing :P  I'll take another look at the local files, and see if I can't see what the blocker is then.

**Comment by brianfreud** [comment]
Ok, found the problem faster than I thought.  Your minified version from https://github.com/LeaVerou/prefixfree/blob/master/prefixfree.min.js works; the minified version from Google's code compressor, run on https://github.com/LeaVerou/prefixfree/blob/master/prefixfree.js , did not.
