### ISSUE TITLE
Errors occurs in script in IE10

### ISSUE THREAD

**Issue by iamvdo** [LeaVerou/prefixfree#44]
Hi,
2 errors occurs in IE10:
- Access is denied (line 89 , ch 3)
- Access is denied (line 125, ch 3)

I don't test on IE9.

**Comment by LeaVerou** [comment]
Does anything happen besides these errors? It's probably a cross-origin thing.

**Comment by iamvdo** [comment]
Nothing happens!

Thus, prefixfree.js is on same folder.

**Comment by LeaVerou** [comment]
Yeah, your stylesheets are cross-origin, not prefixfree. 

Not that it causes problems in that case, just these errors are thrown in IE (only), and of course the cross-origin stylesheets aren't prefixed.

**Comment by iamvdo** [comment]
My stylesheets aren't cross-origin. 

I don't understand the problem.

**Comment by LeaVerou** [comment]
Are you testing locally? Please read the limitations on its project page: http://leaverou.github.com/prefixfree/

**Comment by iamvdo** [comment]
No, i'm not!

**Comment by LeaVerou** [comment]
Hm, ok, this is indeed odd. Do you have an online example?

**Comment by iamvdo** [comment]
Ok, i found the bug: stylesheets from Google WebFonts included with link tag. I had to load it with @import from my main stylesheet.

Is this a reported bug?

**Comment by LeaVerou** [comment]
This _is_ cross-origin!

In any case, you're better off including them as @import anyway. They are presentation, they don't belong in your markup.

Yes, it is a reported bug that IE throws errors on cross-origin stylesheets. A low priority one though, as besides throwing these errors, there doesn't seem to be any other problem.

**Comment by iamvdo** [comment]
Yeah! I didn't think of <em>this</em> stylesheet.
