### ISSUE TITLE
border-image-slice problem

### ISSUE THREAD

**Issue by old9** [LeaVerou/prefixfree#48]
While writing border-image with the shorthand `border-image` rule, since the `border-image-slice` will not be correctly handled by firefox and the whole rule thus will be ignored in that browser.
so, firefox will choke on this
`border-image: url(path/to/img.png) 10 10 10 10 fill round round;`
unless an extra
`-moz-border-image: url(path/to/img.png) 10 10 10 10;`
is presented.

more details:
http://code.google.com/p/chromium/issues/detail?id=101311#c9
http://www.w3.org/TR/css3-background/#border-image-slice-fill

**Comment by LeaVerou** [comment]
I don't see where the -prefix-free bug is, -prefix-free is not a polyfill. It only adds prefixes, if needed.

Btw In that case, I don't see why you need a `-moz-border-image` since the full version will be completely dropped. Just use the cascade:

```
border-image: url(path/to/img.png) 10 10 10 10;
border-image: url(path/to/img.png) 10 10 10 10 fill round round;
```

-prefix-free won't replace proper fallbacks :)
