### ISSUE TITLE
Minified Version Not Working?

### ISSUE THREAD

**Issue by JacobDB** [LeaVerou/prefixfree#5]
I couldn't get the minified version of the script to work in any browser (Chrome 16, Firefox 8, IE9). I tried the uncompressed version, works just fine. Not sure what the issue was.

**Comment by LeaVerou** [comment]
Ugh, probably Google Closure Compiler being an ass. I'll try tomorrow with a different minifier and let you know.

**Comment by JacobDB** [comment]
Thanks :)

**Comment by LeaVerou** [comment]
I just pushed a fix for another issue, so I had to rebuild the minified file (I used the same minifier as always, Closure Compiler). I just tested the minified file and it seems to work. Maybe it was a temporary hiccup. Can you please test?

**Comment by verlok** [comment]
I'm currently using the minified version on my project and it's working.
@revxx14 have your read that with Chrome it's not working on local (unless you set some flag)?

**Comment by LeaVerou** [comment]
Ok, closing this issue. If anyone has issues with the minified version please reopen.
