### ISSUE TITLE
-webkit-flex() function not supported

### ISSUE THREAD

**Issue by bukzor** [LeaVerou/prefixfree#56]
To get the flexbox model working correctly, we need to use "width: flex(1 2)" and similar styles.

I had expected that prefixfree would help with translating those, since it does correctly translate "display: flexbox"

Reference:
http://www.w3.org/TR/css3-flexbox/#multiline

**Comment by LeaVerou** [comment]
Doesn't seem to be in the latest draft: http://dev.w3.org/csswg/css3-flexbox/#multiline
If I'm wrong, feel free to correct me.

Also, how many browsers support this function? I prefer to add only stuff that are eventually going to be unprefixed, but I often make exceptions when it would really help authors.

**Comment by bukzor** [comment]
This is marked as "Latest Draft" from the link you provided.
http://www.w3.org/TR/css3-flexbox/#flex-function

Currently only Chrome 17 implements it. I'll come back when there's wider support I guess.

**Comment by LeaVerou** [comment]
That's the published draft, which is more official. The link I provided is newest (just look at the dates), albeit less official.

If it's only supported by Chrome 17 and is _not_ in the latest ED, that means no new browsers will ever implement it, so you'll always have to deal with only one prefix, until there's no point in using it any more. So, I don't think adding it would offer a significant benefit, unless it makes its way back into the ED.

**Comment by bukzor** [comment]
Thanks for explaining.
