### ISSUE TITLE
Error loading google fonts when prefixfree.js is present

### ISSUE THREAD

**Issue by raskaman** [LeaVerou/prefixfree#6090]
I am getting the following error on Chrome

XMLHttpRequest cannot load http://fonts.googleapis.com/css?family=Tangerine. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://xxxxxxxxx.com' is therefore not allowed access.

font being loaded:
<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Tangerine">

**Comment by ghoshted** [comment]
Same problem.

**Comment by LeaVerou** [comment]
Please, for the love of the flying spaghetti monster, at least read the home page of libraries you download, ABOVE THE FOLD.
I’m not asking you to read the entire website, that could be too much.
I’m not even asking you to read the entire home page.
ABOVE THE FOLD. Is that too much to expect from people?

(and that applies to any library, not just -prefix-free. For your own sake and sanity!)

**Comment by coliff** [comment]
FYI: To solve it add 'data-noprefix' to the linked Google Font.

```
<link href="https://fonts.googleapis.com/css?family=Roboto:400,300,300italic,400italic,100,100italic" rel="stylesheet" type="text/css" data-noprefix>
```
