### ISSUE TITLE
width: fit-content;

### ISSUE THREAD

**Issue by fumoboy007** [LeaVerou/prefixfree#6092]
`fit-content` is left unprefixed. It should be `-moz-fit-content` or `-webkit-fit-content`.

**Comment by LeaVerou** [comment]
Agreed. Same for min-content and max-content. Pull request? It should only take a minute to add.

**Comment by coliff** [comment]
Cool to see prefixfree get an update - will the version number get bumped? It's been on v1.0.7 for a while...
