### ISSUE TITLE
Can't install from bower - no tags found

### ISSUE THREAD

**Issue by tdmalone** [LeaVerou/prefixfree#6116]
On running `bower install --save prefix-free`:

```
Additional error details:
No tags found in git://github.com/LeaVerou/prefixfree.git
Available branches: gh-pages
```

:)

**Comment by TDA** [comment]
@tdmalone Did you see #173 ?

**Comment by tdmalone** [comment]
No I didn't, thanks! I downloaded it manually, but agree with the comment in that issue that 'While the fix worked, this should be resolved to allow easier uptake via bower.' =)

**Comment by TDA** [comment]
@tdmalone I have a PR with steps to tag :) Lets hope it gets tagged so this won't occur in the future :)
