### ISSUE TITLE
Modern syntax of Custom Properties (CSS variables) affects check for prefix

### ISSUE THREAD

**Issue by joyously** [LeaVerou/prefixfree#6129]
This line is supposed to be checking properties for prefixes, but it will also match CSS variables.
https://github.com/LeaVerou/prefixfree/blob/0d3d2a0e6656316f385cd1d57559a19bcbbf2c57/prefixfree.js#L281

**Comment by joyously** [comment]
Would a good solution be
`if (property.charAt(0) === '-') && (property.charAt(1) !== '-')  { `

?

**Comment by LeaVerou** [comment]
@joyously Yup, that should work.

Or, even better, a regex:

`if (/^-[^-]/.test(property))`
