### ISSUE TITLE
Modernize the codebase

### ISSUE THREAD

**Issue by Kompwu** [LeaVerou/prefixfree#6136]
The code is really old, and hard to maintain.
The project begins to die...
If there are people who are up for starting over, It's time to get together!

**Comment by joyously** [comment]
I've made some recent fixes. Some were simple to add on. One was not; it needed to almost duplicate the functionality.

**Comment by LeaVerou** [comment]
@Kompwu Instead of complaining, you could step in and become a maintainer of it. But hey, complaining is easier.

**Comment by LeaVerou** [comment]
I personally don't use -prefix-free anymore in my own projects, since there are way fewer properties these days that need a prefix than back in 2012 when I wrote it.
I do use the conic-gradient polyfill though, and would totally be up for exporting StyleFix into a new project.

**Comment by long-lazuli** [comment]
I'm still using it on codepen, to be able to see the compiled code without the prefixes.
I don't know if it's a sufficient use case to 'starting over' the code though.

Some parts of the code could really be used. Adding polyfill in the browser seems still a good idea to me.

I can't take time to maintain this repo, I just wanted to show some gratitude to this project !

**Comment by Kompwu** [comment]
@LeaVerou I can't do that.
The code is way too old, it'll take months, and I have a job.

I created this issue to get people together to start over.

It will take much less time and I have already started on my own in my spare time.

I've already completed prefix detection.

I'm not just complaining, I'm trying to help. 

Edit:
I think it's better to create a new library, rather than make a V2.

**Comment by LeaVerou** [comment]
Everybody has a job. It didn't take months to write -prefix-free in the first place, it took 1-2 days while also attending a conference, and that was 6 years ago. I would be very wary following anyone's lead that claims it would take months to modernize 500 lines of code. 😂

You're welcome to start your own project (this is what open source is about after all) but it's basic decency to do it on your own platform, not on the project that you're trying to poach. Bye, and good luck!
