### ISSUE TITLE
missing prefix for :placeholder-shown

### ISSUE THREAD

**Issue by joyously** [LeaVerou/prefixfree#6143]
According to CanIuse https://www.caniuse.com/#search=placeholder
`:placeholder-shown` support uses alternate names that are in the selector list for `::placeholder`.

> Partial support in Firefox refers to using the non-standard `:-moz-placeholder` name rather than `:placeholder-shown`.
> Partial support in IE refers to using the non-standard `:-ms-input-placeholder` name rather than `:placeholder-shown`.

**Comment by LeaVerou** [comment]
Yeah, this has come up a lot in the past. -prefix-free doesn't deal with alternate names, it only prefixes when the name is the same. You need to do this one manually.

**Comment by LeaVerou** [comment]
Oh, I see you submitted a PR. I'm fine with that.

**Comment by glOOmyART** [comment]
just fyi: it has not been fixed in the minified version ;)
