### ISSUE TITLE
2 things - Thank you! and Help please (Transition End Events)

### ISSUE THREAD

**Issue by mgregor** [LeaVerou/prefixfree#64]
Lea,

Prefix free rocks!  Keep up the great work.

I cannot tell and I am not sure the best way to test if the prefixfree also handles CSS3 Transition End Events.

See like here - http://stackoverflow.com/questions/5023514/how-do-i-normalize-css3-transition-functions-across-browsers

There seem to be easy solutions, but figure you might consider adding this if it is not there... If it is there then please advise.

Cheers,

Michael Gregor
Velope.tv - Founder

**Comment by LeaVerou** [comment]
No, -prefix-free does not currently handle event names, and I think it's quite hard to do so. 
However, you might find that the properties `PrefixFree.prefix` and `PrefixFree.Prefix` will quite simplify your prefix-related JavaScript. :)
