### ISSUE TITLE
text-justify-last

### ISSUE THREAD

**Issue by AlmogBaku** [LeaVerou/prefixfree#71]
Hey!
First of all, that's a great script! thanks!

second.. this script doesn't handle "text-justify-last"..

~ Almog

**Comment by LeaVerou** [comment]
I find that highly unlikely. Testcase?

**Comment by AlmogBaku** [comment]
i've tested it by:
http://leaverou.github.com/prefixfree/#test-drive

**Comment by LeaVerou** [comment]
Yeah, I mean, are you sure it's supported at all in the browser you're testing?

**Comment by AlmogBaku** [comment]
Hey,
I've already check this css feature in ff and it works well.
I'm not at home right now but according google it shout works at ie and
webkit as well.

~ Almog.

בתאריך יום שני, 21 במאי 2012, Lea Verou כתב:

**Comment by LeaVerou** [comment]
Are you sure you don’t mean `text-align-last`? I can't find any reference to any `text-justify-last` property.

**Comment by AlmogBaku** [comment]
My bad. You right! I mean to "text-align-last"..
"trxt-align-last" not works

בתאריך יום שני, 21 במאי 2012, Lea Verou כתב:

**Comment by LeaVerou** [comment]
Doesn't seem to be supported in WebKit http://css3test.com/#css3-text

Firefox supports it, and it seems to be correctly prefixed by -prefix-free in Firefox.
