### ISSUE TITLE
-prefix-free webpage makes Firefox 13 use 100% CPU

### ISSUE THREAD

**Issue by mgol** [LeaVerou/prefixfree#72]
-prefix-free webpage:
http://leaverou.github.com/prefixfree/
makes the newest Firefox 13 beta on Ubuntu 12.04 64-bit use 100% CPU.

**Comment by LeaVerou** [comment]
This sounds more like a Firefox issue, especially since we're talking about a beta. Or a non-issue, if it can't be reproduced consistently.

**Comment by mgol** [comment]
I've tried with a different profile in safe mode and it's still happening. But it might be a Firefox issue so I reported it here:
https://bugzilla.mozilla.org/show_bug.cgi?id=756964
I hope it's going to be solved, soon, though, as Firefox 13 will hit stable in 2 weeks.

**Comment by LeaVerou** [comment]
Thanks! Does it occur with any other browser?

**Comment by mgol** [comment]
Both Opera 12 beta and Chrome 19 (stable) don't exhibit the problem so it must be Firefox-related. Should've checked that earlier, sorry for bothering you.

**Comment by LeaVerou** [comment]
No probs. :)
Keep in mind that it may not even be related to -prefix-free itself, it might be triggered by something in the -prefix-free homepage. If you have the time/energy, you could try to reduce it a bit and see which of the two it is.

**Comment by mgol** [comment]
I created a local copy of the site using 'wget -r' and removing the prefix-free.js file helps so it has to be sth interacting with it...

**Comment by LeaVerou** [comment]
Do you get the same issue in other websites using -prefix-free? E.g. http://result.dabblet.com/gist/2659956

**Comment by mgol** [comment]
This page works fine. It's pretty simple, though.

**Comment by mgol** [comment]
Minimal example (the prefix-free page with as many elements cut out as possible):
http://mgol.eu/prefixfree_asdgfsaldgsdkfgsdkfgjsdfghsdlkfg
Also, note that high CPU usage happens almost only when the tab is active.

**Comment by mgol** [comment]
Most of the CPU usage spike is caused my -moz-animation.

**Comment by coolno9** [comment]
I am facing the same issue on Firefox 13.0.1 too. CPU usage shoots up to 100% when prefix-free-min is included on the page. This problem emerged when I updated my Firefox/Ubuntu two days back, so I am inclined to believe some changes in newer version of Firefox are breaking it. 

Any pointers/solutions so far? 

[Edited out 'browser crash' issue, could not replicate. CPU usage pushing to 100% persists. ]

**Comment by mgol** [comment]
That's unfortunate, crashes in this regard shouldn't happen in Firefox 13.x. Are you sure crashes are related to -prefix-free? The mentioned bug was fixed so it's highly probable it's a different issue...

CPU spike is a different issue and I have already cornered it down to -moz-animation.

Relevant bugs:
CPU spike: https://bugzilla.mozilla.org/show_bug.cgi?id=756964
Crash: https://bugzilla.mozilla.org/show_bug.cgi?id=739858

Please, subscribe, vote for this bug and - most importantly - confirm you experience it. It makes it more probable it gets fixed, so far I'm the only one who has reported it.

**Comment by mgol** [comment]
I meant the "CPU spike" bug obviously, the other one is closed so the only thing you can do is to report a new issue about it. :)

**Comment by coolno9** [comment]
@mzgol Edited my response above, and voted on the CPU spike bug reported by you.

**Comment by mgol** [comment]
Could you also comment that you experience the issue (together with your OS/browser configuration)? The bug is still in UNCONFIRMED state so it needs such comments.

**Comment by coolno9** [comment]
Ubuntu 11.04 - the Natty Narwhal/ Firefox 13.0.1. The application is in my local, so I'll re-confirm after deployment also; check for other OS/Browser combinations shortly.)

**Comment by mgol** [comment]
I meant confirming in a comment on bugzilla, not here...
