### ISSUE TITLE
background-clip: text; not being prefixed

### ISSUE THREAD

**Issue by franciscolourenco** [LeaVerou/prefixfree#74]
I believe this only works in webkit currently.

**Comment by LeaVerou** [comment]
If you want to use non-standard stuff, type their prefixes. That's the policy. I'll never make it easier for developers to use non-standard crap, sorry :)

**Comment by franciscolourenco** [comment]
The crap you are supporting is all non-standard, otherwise there wouldn't be the need for prefixes in the first place.

**Comment by LeaVerou** [comment]
There is a difference between experimental implementations of draft standards and proprietary stuff that's not specified anywhere. `-webkit-background-clip: text` falls into the latter category.

**Comment by franciscolourenco** [comment]
That sounds better :)

**Comment by LeaVerou** [comment]
Sorry if my first response came off as a bit rude, I'm not in the best mood today. Anyway, if you want to learn more about the distinction, a while ago I wrote an article about it: http://www.alistapart.com/articles/every-time-you-call-a-proprietary-feature-css3-a-kitten-dies/

**Comment by franciscolourenco** [comment]
Good article, thank you!
