### ISSUE TITLE
Broken when stylesheet URL contains RegExp chars like +

### ISSUE THREAD

**Issue by gotcha** [LeaVerou/prefixfree#81]
Behavior RegExp is broken:

SyntaxError: Invalid regular expression /bla/: Nothing to repeat

Base URL needs to be escaped before being used in a RegExp.

**Comment by LeaVerou** [comment]
Gah, right. Confirmed, thanks! This should be pretty easy to fix, provided I get some time to address it.

**Comment by LeaVerou** [comment]
Fixed, so closed. Thanks again :)

**Comment by gotcha** [comment]
How does the fix gets included in prefixfree.min.js ?

**Comment by LeaVerou** [comment]
It doesn’t — somebody has to manually do it.

**Comment by gotcha** [comment]
Which minifier do you use ?

This way, I can do it !

**Comment by LeaVerou** [comment]
I alternate between uglifyJS and Closure Compiler. But any other good minifier is fine.

**Comment by gotcha** [comment]
Is there a convention for version numbers like 1.0.2 and 1.0.6 ?

When do you bump those ?

**Comment by LeaVerou** [comment]
When it feels right. 

I guess you may bump the StyleFix version. Not the prefixfree version though.

**Comment by gotcha** [comment]
In the Zope/Plone community, we include the changelog in the READMEs.
This way, it is much easier to know which version you need to get a fix for a given bug.

**Comment by LeaVerou** [comment]
What’s the point of that? Can’t somebody just check the commits?

**Comment by gotcha** [comment]
If I do not follow closely a project, it is much easier to scan a CHANGELOG than to check each commit.

**Comment by LeaVerou** [comment]
This sounds like a fix to a badly organized commits history. Why not just try to keep the commit history as neat as possible? (not saying I manage to, but I try...)

**Comment by gotcha** [comment]
When the CHANGELOG is available, it is much easier to get a hint if a bug I hit has already been solved in a later release.

But, I do not want to argue/troll. It was just a suggestion.

**Comment by LeaVerou** [comment]
I’m not against the idea, I’m just afraid it will get out of sync very quickly. I wish there was a way to do it automatically through the commits history (e.g. highlight the most important commits or something)

**Comment by gotcha** [comment]
It is true that it takes a while until it is a habit. Nevertheless, once a community gets used, it really brings value. I'll try to make a change log that makes sense and propose it as a pull request.
