### ISSUE TITLE
Unprefixed linear-gradient values use "to" keyword

### ISSUE THREAD

**Issue by JoshTumath** [LeaVerou/prefixfree#87]
The spec now uses "to" to give the position of a gradient.

e.g.
Old: linear-gradient(top, ...
New: linear-gradient(to bottom, ...

Now that IE10 supports the correct syntax unprefixed, it's important that this is fixed.

**Comment by LeaVerou** [comment]
-prefix-free just adds prefixes, it doesn’t modify your code otherwise. Also, some prefixed implementations use `to` as well (modern Firefox and Opera at least). Your best bet is to use both, like so:

```
background: linear-gradient(top, white, black);
background: linear-gradient(to bottom, white, black);
```
