### ISSUE TITLE
-webkit-overflow-scrolling does not get prefixed.

### ISSUE THREAD

**Issue by Grezzo** [LeaVerou/prefixfree#88]
Thanks for the great script. It makes css3 stuff some much more fun to dabble with.

I found a property that does not get prefixed: If I put `overflow-scrolling: touch;` in my css, I was expecting it be become `-webkit-overflow-scrolling: touch;`, but it didn't get prefixed.

As a work around, I have had to put the prefixed property in my css.

See here for Apple's documentation on that css property: http://developer.apple.com/library/safari/#documentation/appleapplications/reference/safaricssref/articles/standardcssproperties.html

**Comment by LeaVerou** [comment]
-prefix-free is not for prefixing non-standard stuff with no spec (not even a draft one).

That said, I find it very weird that that property doesn’t get prefixed (although it's not technically a bug). Maybe an unprefixed one exists with the same name? That would explain it.

**Comment by Grezzo** [comment]
Fair enough, I agree that it is non-standard, and as it's seems like it's only ever going to be used for mobile webkit it won't ever need any other prefixes, so I'll just prefix it myself.

I don't _think_ it's available unprefixed, but it doesn't really matter.

Again, thanks for the great script, it's nice to have such a quick reply for something that is free to use.
