### ISSUE TITLE
Display: flex; not prefixed

### ISSUE THREAD

**Issue by wouterj** [LeaVerou/prefixfree#89]
The flexibele box model CSS3 features' `display: flex;` on the parent should be prefixed:

```
#parent {
    display: flex;
}
/* should be */
#parent {
    display: -webkit-flex;
    display: -moz-flex;
    display: -ms-flex;
    display: -o-flex;
    display: flex;
}
```

**Comment by LeaVerou** [comment]
Have you tried this in a browser that actually supports `display: flex` with a prefix, and it didn't work?

**Comment by wouterj** [comment]
Yes, I tried this in Chrome 21.0.1180.15 dev-m. You can see my test here: http://codepen.io/WouterJ/pen/6/1

**Comment by LeaVerou** [comment]
Strange. Marking this as confirmed for now, will need to test more thoroughly later.

**Comment by LeaVerou** [comment]
Btw, are you using the latest version? I remember I added the `flex` value fairly recently. I guess you are, but figured I’d ask, just in case.

**Comment by wouterj** [comment]
Excuse me, I assumed codepen uses the latest version of prefix free, but it turns out that it is an older version. I have done the same test on my localhost, with the latest version, and it works.

Thank you for creating this very usefull plugin and excuse me for my wrong issue!

**Comment by LeaVerou** [comment]
Phew! No problem. Closing this.

**Comment by crispen-smith** [comment]
I understand this is closed as working correctly but I was wondering if there was an opportunity around documentation as Flex does present a special case (box-align vs. align-contents), a quick note indicating whether we need to include both or if prefix-free resolves it would be fantastic to erase questions on this front.

The flex property:
