### ISSUE TITLE
Server-side solution?

### ISSUE THREAD

**Issue by shazdeh** [LeaVerou/prefixfree#9]
Please don't kill me by asking this! But I really prefer to handle this in server and hand a clean stylesheet to the browser. Do you know a PHP version of this?

**Comment by verlok** [comment]
Lea wrote about server-side on this page
http://leaverou.github.com/prefixfree/
Is this the answer you're looking for?

**Comment by LeaVerou** [comment]
No, I don't. I guess you could use some preprocessor like LESS or SASS and a few mixins to add prefixes.

**Comment by kottenator** [comment]
Your solution is beautiful, it works exactly how it should work: I don't have to add prefixes manually and I don't have to support them.

But it would be just great if you add server-side solution too (e.g. as NodeJS plugin). Using LESS / SASS mixins is not as good as -prefix-free

**Comment by facundocabrera** [comment]
Maybe https://github.com/nDmitry/grunt-autoprefixer could helps :D

2014-01-30 Rostyslav Bryzgunov notifications@github.com
